spring:
  mongodb:
    uri: ${MONGODB_URI}
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS}

server:
  port: ${PORT:8080}

services:
  auth-service:
    url: ${AUTH_SERVICE_URL:http://auth-service}
  message-service:
    url: ${MESSAGE_SERVICE_URL:http://message-service}
