FROM eclipse-temurin:25-jdk AS builder

# elogateway has no contract dependencies
WORKDIR /build/elogateway
COPY elogateway .
RUN chmod +x gradlew && ./gradlew bootJar --no-daemon && \
    find ./build/libs -name "*.jar" ! -name "*-plain.jar" -exec cp {} ./app.jar \;

FROM eclipse-temurin:25-jre
COPY --from=builder /build/elogateway/app.jar app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]
