FROM eclipse-temurin:25-jdk AS builder

# file-service has no external contract dependencies
WORKDIR /build/file-service
COPY file-service .
RUN chmod +x gradlew && ./gradlew :file-service-impl:bootJar --no-daemon && \
    find ./file-service-impl/build/libs -name "*.jar" ! -name "*-plain.jar" -exec cp {} ./app.jar \;

FROM eclipse-temurin:25-jre
COPY --from=builder /build/file-service/app.jar app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]
