spring:
  mongodb:
    uri: mongodb://root:admin12345@localhost:27017/elocampo?authSource=admin
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092
server:
  port: 8086

services:
  auth-service:
    url: http://localhost:8080
