spring:
  application:
    name: account-service
  flyway:
    enabled: false
  mongodb:
    auto-index-creation: true
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${BREVO_SMTP_USERNAME}
    password: ${BREVO_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    context-path: /rest

email:
  from: ${EMAIL_FROM}
