spring:
  mongodb:
    uri: mongodb://root:admin12345@localhost:27017/elocampo?authSource=admin
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092
  mail:
    username: ${BREVO_SMTP_USERNAME}
    password: ${BREVO_SMTP_PASSWORD}

server:
  port: 8085

services:
  auth-service:
    url: http://localhost:8080

email:
  from: doetechauth@gmail.com
