spring:
  mongodb:
    uri: ${MONGODB_URI}
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS}

server:
  port: ${PORT:8080}

services:
  account-service:
    url: ${ACCOUNT_SERVICE_URL:http://account-service}
