spring:
  application:
    name: elogateway

token:
  secret: "${TOKEN_SECRET:QNyrmdUkpqi+Z7rPCrigN3dvLwbwxNz33d5r2STdr2M=}"
  public-endpoints:
    - method: POST
      path: /rest/v1/token
    - method: POST
      path: /rest/v1/user
    - method: POST
      path: /rest/v1/user/reset-password/**
    - method: POST
      path: /rest/v1/account
