name: Deploy account-service

on:
  push:
    branches:
      - main
    paths:
      - 'src/Backend/account-service/**'
      - 'src/Backend/Dockerfile.account-service'
      - '.github/workflows/account-service-deploy.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AUTHSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AUTHSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AUTHSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Login no ACR
        run: az acr login --name elocampoacr

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src/Backend
          dockerfilePath: Dockerfile.account-service
          registryUrl: elocampoacr.azurecr.io
          registryUsername: ${{ secrets.ELOCAMPO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ELOCAMPO_REGISTRY_PASSWORD }}
          containerAppName: account-service
          containerAppEnvironment: elocampo-env
          resourceGroup: elocampo-rg2
          imageToBuild: elocampoacr.azurecr.io/account-service:${{ github.sha }}
          targetPort: 8080
          ingress: internal
